locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    path('live_idea/', views.LiveIdeaTableView.as_view(), name='living_idea'),
    re_path(r'^new_idea/$', views.ilaksa_new, name='new_idea'),
    path('live_idea/<uuid:pk>/', views.EditData, name='edit_idea'),
]

catalog/models.py
from django.db import models
import uuid

# Create your models here.

class ilaksa(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=200, help_text="Краткое описание идеи", verbose_name="Название")
    descr = models.TextField(max_length=1000, help_text="Описание идеи подробнее", blank=True, verbose_name="Описание")
    date_start = models.DateField(verbose_name="Дата начала")

    STATUS_IDEA = (
        ('t', 'Реальна'),
        ('z', 'Забил хуй'),
    )

    status_idea = models.CharField(max_length=1, choices=STATUS_IDEA, default='t',
    help_text='Что с идеей Айлаксы сейчас', verbose_name="Статус идеи")
    date_finish = models.DateField(null=True, blank=True, verbose_name="Дата окончания")

    class Meta:
        ordering = ["date_start"]

    def __str__(self):
        return f'{self.id} ({self.name})'
    

catalog/forms.py
from django import forms
from django.forms import ModelForm

from catalog.models import ilaksa

class CreateFrom(ModelForm):
    name = forms.CharField(max_length=200, label="Название")
    name.widget.attrs.update({'autocomplete': 'off'})
    descr = forms.CharField(max_length=1000, required=False, label="Краткое описание идеи")
    descr.widget.attrs.update({'autocomplete': 'off'})
    date_start = forms.DateField(input_formats=['%d/%m/%Y'])
    date_start.widget.attrs.update({'autocomplete': 'off'})

    STATUS_IDEA = (
        ('t', 'Реальна'),
        ('z', 'Забил хуй'),
    )

    status_idea = forms.ChoiceField(choices=STATUS_IDEA,
    label="Статус идеи")
    date_finish = forms.DateField(required=False, input_formats=['%d/%m/%Y'])
    date_finish.widget.attrs.update({'autocomplete': 'off'})
    class Meta:
        model = ilaksa
        fields = ['name', 'descr', 'date_start', 'status_idea', 'date_finish']

class EditForm(ModelForm):
    new_descr = forms.CharField(max_length=1000, required=False, label="Краткое описание идеи")
    STATUS_IDEA = (
        ('t', 'Реальна'),
        ('z', 'Забил хуй'),
    )

    status_idea = forms.ChoiceField(choices=STATUS_IDEA,
    label="Статус идеи")
    date_finish = forms.DateField(required=False, input_formats=['%d/%m/%Y'])
    date_finish.widget.attrs.update({'autocomplete': 'off'})
    class Meta:
        model = ilaksa
        fields = ['descr', 'status_idea', 'date_finish']

catalog/views.py
from dataclasses import fields
from urllib import request
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.models import ilaksa
from .forms import CreateFrom, EditForm
from .tables import ProductTable
from django_tables2 import SingleTableView
from django.views.generic.edit import UpdateView

def index(request):
    num_idea=ilaksa.objects.all().count()
    num_live_idea=ilaksa.objects.filter(status_idea='t').count()
    num_dead_idea=ilaksa.objects.filter(status_idea='z').count()

    return render(
        request,
        'index.html',
        context={'num_idea':num_idea,'num_live_idea':num_live_idea, 'num_dead_idea':num_dead_idea},
    )

class LiveIdeaTableView(SingleTableView):
    model = ilaksa
    table_class = ProductTable

def ilaksa_new(request):
    if request.method == 'POST':
        form = CreateFrom(request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse(index))
    else:
        form = CreateFrom()
    return render(
        request,
        'ilaksa_new.html',
        {'form': form}
    )

def EditData(request, pk):
    ilaksa_inst = get_object_or_404(ilaksa, pk=pk)
    if request.method == 'POST':
        form = EditForm(request.POST)
        if form.is_valid():
            ilaksa_inst.descr = form.cleaned_data["descr"]
            ilaksa_inst.status_idea = form.cleaned_data["status_idea"]
            ilaksa_inst.date_finish = form.cleaned_data["date_finish"]
            ilaksa_inst.save()
        return HttpResponseRedirect(reverse(index))
    else:
        form = EditForm()
    return render(
        request,
        'catalog/edit_data.html',
        {'form': form}
    )

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="ru">
<head>

  {% block title %}<title>iLuxa</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
        <div class="list-group list-group-flush mx-3 mt-4">
          <a href="{% url 'index' %}" class="list-group-item list-group-item-action py-2 ripple">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
              <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
            </svg><span> Основная страница</span>
          </a>
          <a href="{% url 'living_idea' %}" class="list-group-item list-group-item-action py-2 ripple">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-table" viewBox="0 0 16 16">
              <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm15 2h-4v3h4V4zm0 4h-4v3h4V8zm0 4h-4v3h3a1 1 0 0 0 1-1v-2zm-5 3v-3H6v3h4zm-5 0v-3H1v2a1 1 0 0 0 1 1h3zm-4-4h4V8H1v3zm0-4h4V4H1v3zm5-3v3h4V4H6zm4 4H6v3h4V8z"/>
            </svg><span> Страница живых</span>
          </a>
          <a href="{% url 'new_idea' %}" class="list-group-item list-group-item-action py-2 ripple">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard-plus" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M8 7a.5.5 0 0 1 .5.5V9H10a.5.5 0 0 1 0 1H8.5v1.5a.5.5 0 0 1-1 0V10H6a.5.5 0 0 1 0-1h1.5V7.5A.5.5 0 0 1 8 7z"/>
              <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
              <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
            </svg><span> Создать новое</span></a
          >
        </div>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

catalog/templates/catalog/edit_data.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}

<form method="post" padding-top="20px">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-default" type="submit" value="Отправить" />
</form>
<script>
$(function () {
    $("#id_date_finish").datepicker({
      format:'dd/mm/yyyy',
      autoHide: true,
      language: 'ru-RU'
    });
  });
</script>
{% endblock %}

catalog/templates/catalog/ilaksa_list.html
{% extends "base_generic.html" %}
{% load render_table from django_tables2 %}

{% block content %}
  {% render_table table %}
{% endblock %}

catalog/templates/ilaksa_new.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-default" type="submit" value="Отправить" />
</form>
<script>
    $(function () {
      $("#id_date_start").datepicker({
        format:'dd/mm/yyyy',
        autoHide: true,
        language: 'ru-RU'
      });
    });
    $(function () {
      $("#id_date_finish").datepicker({
        format:'dd/mm/yyyy',
        autoHide: true,
        language: 'ru-RU'
      });
    });
</script>
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1><strong>iLuxa</strong></h1>
<h2>Что это вообще?</h2>

  <p>Представим ситуацию, что ваш друг <strong>Илья</strong> любит пустословить и обещать что-то просто так? Вы уже начали забывать, что он говорил? <br> С сервисом <strong>iLuxa</strong> вы можете сортировать все, что было сказано!</p>

<h2>Так, и как тут работать?</h2>

  <p>Все очень просто! Если вы хотите посмотреть то, что уже было наобещано, то заходите <a href="{% url 'living_idea' %}">сюда</a>, а если вы хотите добавить свое, <a href="{% url 'new_idea' %}">то добавляйте здесь!</a></p>

{% endblock %}